apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
  namespace: network
spec:
  addresses: # range of IP addresses to be used by MetalLB
    - "192.168.1.110-192.168.1.130"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: network
spec:
  ipAddressPools:
    - local-pool
