apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
  namespace: network
spec:
  addresses:
    - 192.168.1.64/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: network
spec:
  ipAddressPools:
    - local-pool
