name: wikijs
services:
    wiki:
        container_name: Wiki.js
        image: ghcr.io/requarks/wiki:2
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '0.2'
                reservations:
                    memory: 256M
                    cpus: '0.1'
        depends_on:
            - wiki-db
        environment:
            DB_TYPE: postgres
            DB_HOST: wiki-db
            DB_PORT: 5432
            DB_USER: wikijs
            DB_PASS: yourpassword
            DB_NAME: wiki
        restart: unless-stopped
        ports:
            - "9932:3000"
    wiki-db:
        container_name: Wiki-DB
        image: postgres:15-alpine
        deploy:
            resources:
                limits:
                    memory: 256M
                    cpus: '0.2'
                reservations:
                    memory: 64M
                    cpus: '0.1'
        environment:
            POSTGRES_DB: wiki
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_USER: wikijs
        logging:
            driver: none
        restart: unless-stopped
        volumes:
            - /DATA/AppData/wiki-db:/var/lib/postgresql/data
