name: pihole
services:
  pihole:
    container_name: Pi-hole
    image: docker.io/pihole/pihole:2025.06.2
    hostname: damian-pihole
    network_mode: bridge
    dns:
      - 1.1.1.1 # Cloudflare IPv4
      - 8.8.8.8 # Google IPv4
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.6'
        reservations:
          memory: 256M
          cpus: '0.3'
    environment:
      PROXY_LOCATION: pi.hole
      TZ: America/Sao_Paulo
      VIRTUAL_HOST: pi.hole
      WEBPASSWORD: pihole123
      FTLCONF_dns_listeningMode: "all"
      DNS_FQDN_REQUIRED: "false"
      DNS_BOGUS_PRIV: "false"
      DNSSEC: "false"
    ports:
      - "8800:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "547:547/udp"
    restart: unless-stopped
    volumes:
      - /AppData/pihole/etc/pihole:/etc/pihole
      - /AppData/pihole/etc/dnsmasq.d:/etc/dnsmasq.d

# blocking pages list
# https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/refs/heads/main/Pornpages.txt
# https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/refs/heads/main/Telemetry.txt
# https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/refs/heads/main/Malicious.txt
# https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/refs/heads/main/Adsandtrackers.txt