name: pihole
services:
  pihole:
    container_name: Pihole
    image: docker.io/pihole/pihole:2024.07.0
    hostname: pihole
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.6'
        reservations:
          memory: 256M
          cpus: '0.3'
    environment:
      PROXY_LOCATION: pi.hole
      TZ: America/Sao_Paulo
      VIRTUAL_HOST: pi.hole
      WEBPASSWORD: pihole123
      FTLCONF_dns_upstreams: "1.1.1.1,8.8.8.8"
      DNS_FQDN_REQUIRED: "false"
      DNS_BOGUS_PRIV: "false"
      DNSSEC: "false"
    ports:
      - "8800:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "547:547/udp"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/pihole/etc/pihole:/etc/pihole
      - /DATA/AppData/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
