name: pihole

services:
  pihole:
    container_name: Pihole
    image: docker.io/pihole/pihole:2024.07.0
    hostname: pihole
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.6'
        reservations:
          memory: 256M
          cpus: '0.3'
    environment:
      - PROXY_LOCATION: pi.hole
      - TZ: America/Sao_Paulo
      - VIRTUAL_HOST: pi.hole
      - WEBPASSWORD: pihole123
    network_mode: bridge
    ports:
      - "8800:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "547:547/udp"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/pihole/etc/pihole:/etc/pihole
      - /DATA/AppData/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
