name: myspeed
services:
    myspeed:
        container_name: MySpeed
        image: germannewsmaker/myspeed:1.0.9
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '0.3'
                reservations:
                    memory: 128M
                    cpus: '0.1'
        ports:
            - "5216:5216"
        volumes:
            - /DATA/AppData/myspeed:/myspeed/data
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:5216" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s
