name: syncthing
services:
  syncthing:
    container_name: Syncthing
    hostname: Damian
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.6"
        reservations:
          memory: 256M
          cpus: "0.2"
    environment:
      PGID: "1000"
      PUID: "1000"
    image: docker.io/syncthing/syncthing:1.30
    ports:
      - "8384:8384"
      - "22000:22000"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: always
    stop_grace_period: 1m0s
    volumes:
      - /home/drew/Syncthing:/var/syncthing
      - /AppData/syncthing/media/data/syncthing:/media/data/syncthing
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fkLsS",
          "-m",
          "2",
          "http://127.0.0.1:8384/rest/noauth/health",
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: syncthing_default
