image:
  repository: deluan/navidrome
  tag: "0.55.2"
  pullPolicy: IfNotPresent

env:
  TZ: "America/Sao_Paulo"
  ND_LOGLEVEL: debug
  ND_SESSIONTIMEOUT: 72h
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_MUSICFOLDER: /music
  ND_SCANSCHEDULE: 1h
  ND_BASEURL: ""

service:
  main:
    ports:
      http:
        port: 4533

resources:
  limits:
    memory: 1Gi
    cpu: 768m
  requests:
    memory: 256Mi
    cpu: 256m

persistence:
  config:
    enabled: true
    type: pvc
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /data
    existingClaim: navidrome-config-pvc

  music:
    enabled: true
    type: hostPath
    hostPath: /mnt/ace/Sync/Music
    mountPath: /music
    readOnly: false

ingress:
  main:
    enabled: false
