name: DomiCraft
services:
  minecraft:
    container_name: Minecraft
    build: .
    environment:
      EULA: "TRUE"
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
      - "25575:25575"
      - "19132:19132/udp"
    volumes:
      - /AppData/domicraft:/data
    restart: unless-stopped

volumes:
  domicraft: {}