name: homarr
services:
  homarr:
    container_name: Homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/homarr:/appdata
    env_file:
      - ./homarr.env
    ports:
      - '7575:7575'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:7575" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
