apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/pihole"
