image:
  repository: "pihole/pihole"
  tag: "2025.04.0"
  pullPolicy: IfNotPresent

adminPassword: "admin"

DNS1: "1.1.1.1"
DNS2: "8.8.8.8"

persistentVolumeClaim:
  enabled: true

serviceDhcp:
  enabled: false

serviceDns:
  loadBalancerIP: 192.168.1.113
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  nameservers:
    - 1.1.1.1
    - 8.8.8.8
